services:
  db:
    image: postgres:16-alpine
    container_name: horaclass-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hcdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Descomenta si necesitas conectar DBeaver/psql desde el host:
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hcdb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: horaclass-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hcdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: INFO
      LOGGING_LEVEL_ORG_HIBERNATE: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: INFO
      LOGGING_LEVEL_CO_EDU_UNBOSQUE: INFO
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/actuator/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 90s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: horaclass-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8081:80"

volumes:
  postgres_data:
