events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html index.htm;

        # MIME types para Vite
        location ~* \.tsx?$ {
            types { } default_type application/javascript;
        }
        location ~* \.(js|mjs|jsx|ts|tsx)$ {
            types { } default_type application/javascript;
            try_files $uri /index.html;
        }
        location ~* \.(css|less|scss|sass|styl|stylus|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
            try_files $uri =404;
        }

        # React Router SPA
        location / {
            try_files $uri $uri/ /index.html;
        }

        # API Backend
        location /api/ {
            proxy_pass http://backend:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}