

sonar.projectKey=horaclass
sonar.projectName=HoraClass

sonar.organization=4ng13-60rd1770

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/target/**,**/package-lock.json

sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.typescript.tsconfigPath=frontend/tsconfig.json
