spring.application.name=horaclass
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hcdb}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

spring.jpa.hibernate.ddl-auto=update
spring.app.jwtSecret=${JWT_SECRET:TmJN8fgP7ArCl6Gpx5+iVInlUon0vLjs8JYE15LHiUM=}
spring.app.jwtExpirationMS=28800000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.co.edu.unbosque=DEBUG