spring.application.name=horaclass
spring.datasource.url=jdbc:postgresql://localhost:5432/HCDB
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

spring.jpa.hibernate.ddl-auto=validate
spring.app.jwtSecret=TmJN8fgP7ArCl6Gpx5+iVInlUon0vLjs8JYE15LHiUM=
spring.app.jwtExpirationMS=300000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.co.edu.unbosque=DEBUG